### Get Docs Manifest
GET http://localhost:7632/api/v1/identity/docs
Accept: application/json


### Get single doc
GET http://localhost:7632/api/v1/identity/docs/iam-quickstart
Accept: application/json