server:
  port: ${SERVER_PORT:8087}

spring:
  datasource:
    url: ${DEV_DATASOURCE_URL:jdbc:postgresql://localhost:5432/iam_db}
    username: ${DEV_DATASOURCE_USERNAME:postgres}
    password: ${DEV_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

nats:
  url: ${DEV_NATS_URL:nats://localhost:4222}
  username: ${DEV_NATS_USERNAME:}
  password: ${DEV_NATS_PASSWORD:}

eureka:
  client:
    service-url:
      defaultZone: ${DEV_EUREKA_URL:http://localhost:8761/eureka/}
