server:
  port: ${SERVER_PORT:8082}

spring:
  config:
    import: "optional:file:src/main/resources/.env-staging[.properties]"
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://postgres-staging:5432/iam_db}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: ${JWT_EXPIRATION:86400000}

instance:
  token:
    secret: ${INSTANCE_TOKEN_SECRET:6A576E5A7234753778214125442A472D4B6150645367566B5970337336763979}

nats:
  url: ${NATS_URL:nats://nats-staging:4222}
  username: ${NATS_USERNAME:}
  password: ${NATS_PASSWORD:}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
