name: Prod deployment.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  prod-test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run tests
        run: mvn clean

  prod-build-and-push:
    runs-on: ubuntu-latest
    needs: prod-test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: qarani/iam-server:prod
          build-args: |
            SPRING_PROFILES_ACTIVE=prod

  prod-deploy:
    needs: prod-build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Deploy IAM Server (Swarm)
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.PROD_HOST }}
            username: ${{ secrets.PROD_USERNAME }}
            key: ${{ secrets.PROD_SSH_KEY }}
            script: |
              set -e

              echo "Ensuring overlay network exists..."
              docker network create --driver overlay prod-overlay-net || true

              echo "Pulling latest image..."
              docker pull qarani/iam-server:prod

              echo "Removing old service..."
              docker service rm iam-server-prod || true

              echo "Deploying iam-server-prod..."

              docker service create \
                --name iam-server-prod \
                --network aws-prod-network \
                --publish published=7632,target=7632 \
                --replicas 1 \
                --env SPRING_PROFILES_ACTIVE=prod \
                --env SERVER_PORT=7632 \
                --env DATASOURCE_URL=jdbc:postgresql://postgres-prod:5432/iam_db \
                --env DATASOURCE_USERNAME=postgres-prod-user \
                --env DATASOURCE_PASSWORD=postgres-prod-password \
                --env JPA_SHOW_SQL=true \
                --env JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437 \
                --env JWT_EXPIRATION=86400000 \
                --env INSTANCE_TOKEN_SECRET=6A576E5A7234753778214125442A472D4B6150645367566B5970337336763979 \
                --env NATS_URL=nats://nats-prod:4222 \
                --env NATS_USERNAME=nats-prod-user \
                --env NATS_PASSWORD=nats-prod-password \
                --env EUREKA_URL=http://discovery-server-prod:8761/eureka/ \
                --env NATS_SUBJECT_PREFIX=prod.v1 \
                qarani/iam-server:prod

              echo "IAM server deployed."
