name: Prod deployment.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  prod-test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run tests
        run: mvn clean

  prod-build-and-push:
    runs-on: ubuntu-latest
    needs: prod-test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: qarani/iam-server:prod
          build-args: |
            SPRING_PROFILES_ACTIVE=prod

  prod-deploy:
    needs: prod-build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Deploy to Prod via SSH over Tailscale
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            docker pull qarani/iam-server:prod
            docker stop iam-server-prod || true
            docker rm iam-server-prod || true
            docker run -d --name iam-server-prod -p 8061:8061 \
              --network aws-prod-network \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SERVER_PORT=8061 \
              -e DATASOURCE_URL=jdbc:postgresql://postgres-prod:5432/iam_db \
              -e DATASOURCE_USERNAME=postgres-prod-user \
              -e DATASOURCE_PASSWORD=postgres-prod-password \
              -e JPA_SHOW_SQL=true \
              -e JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437 \
              -e JWT_EXPIRATION=86400000 \
              -e INSTANCE_TOKEN_SECRET=6A576E5A7234753778214125442A472D4B6150645367566B5970337336763979 \
              -e NATS_URL=nats://nats-prod:4222 \
              -e NATS_USERNAME=nats-prod-user \
              -e NATS_PASSWORD=nats-prod-password \
              -e EUREKA_URL=http://discovery-server-prod:8761/eureka/ \
              -e NATS_SUBJECT_PREFIX=prod.v1 \
              qarani/iam-server:prod
